# 임대료 데이터 정리
### 1. 데이터 프레임 만들기 (201808)
1) 임대료 데이터 불러오기  
2) 임대료 데이터 동별로 정리하기
3) 임대료 데이터 동별로 dataframe 만들기

In [53]:
import numpy as np
import pandas as pd
import re

In [54]:
#임대료 데이터 불러오기
df = pd.read_excel('realestate_201808.xlsx')

In [55]:
df.head(2)

,시군구,유형,지번,도로명,용도지역,건축물주용도,전용/연면적(㎡),대지면적(㎡),거래금액(만원),1㎡당금액(만원),층,계약년월,계약일,지분구분,건축년도
0,서울특별시 강남구 논현동,집합,1**,학동로26길,제1종일반주거,제2종근린생활,38.64,,"19,000",491.718427,NaN,201807,11~20,,2018.0
1,서울특별시 강남구 논현동,집합,2**,봉은사로,일반상업,숙박,30.03,,"20,000",666.000666,12.0,201807,21~31,,2003.0

In [56]:
 real_estate= df[['시군구', '1㎡당금액(만원)']]

In [57]:
real_estate.head(20)

              시군구    1㎡당금액(만원)
0   서울특별시 강남구 논현동   491.718427
1   서울특별시 강남구 논현동   666.000666
2   서울특별시 강남구 논현동   941.176471
3   서울특별시 강남구 논현동   562.491080
4   서울특별시 강남구 대치동  1400.560224
5   서울특별시 강남구 대치동  1512.027491
6   서울특별시 강남구 대치동   797.101449
7   서울특별시 강남구 대치동   796.703297
8   서울특별시 강남구 대치동  1461.988304
9   서울특별시 강남구 대치동   649.332197
10  서울특별시 강남구 대치동  1400.560224
11  서울특별시 강남구 대치동   539.099220
12  서울특별시 강남구 대치동  1505.481918
13  서울특별시 강남구 대치동   825.954804
14  서울특별시 강남구 대치동  3916.913947
15  서울특별시 강남구 대치동   796.703297
16  서울특별시 강남구 도곡동  1112.295665
17  서울특별시 강남구 도곡동  1145.721446
18  서울특별시 강남구 도곡동   813.953488
19  서울특별시 강남구 도곡동   813.953488

In [58]:
#우선 동별 데이터를 불러올수 있는지 확인해본다
#그리고 동별 1㎡당금액(만원) 을 평균을 낼수 있는지 확인해본다 
# 나중에 배달 데이터랑 확인해본다

In [59]:
dong = real_estate.groupby(['시군구'])[('1㎡당금액(만원)')].sum()

In [60]:
dong.head(20)

시군구
서울특별시 강남구 논현동     2661.386643
서울특별시 강남구 대치동    15602.426371
서울특별시 강남구 도곡동     3885.924088
서울특별시 강남구 삼성동     2878.826349
서울특별시 강남구 수서동     4429.128471
서울특별시 강남구 신사동     6062.996005
서울특별시 강남구 역삼동    25746.908812
서울특별시 강남구 일원동      619.237148
서울특별시 강남구 청담동     5023.873573
서울특별시 강동구 고덕동      251.256281
서울특별시 강동구 길동      7261.362138
서울특별시 강동구 둔촌동     8759.515539
서울특별시 강동구 명일동     2089.903614
서울특별시 강동구 성내동     3180.419819
서울특별시 강동구 암사동      127.877238
서울특별시 강동구 천호동    11938.645909
서울특별시 강북구 미아동      400.000000
서울특별시 강북구 번동       372.402979
서울특별시 강북구 수유동     1891.780276
서울특별시 강서구 가양동      236.167341
Name: 1㎡당금액(만원), dtype: float64

In [61]:
# 각동별로 평균내기
# 배달 데이터랑 부동산 데이터 병합하기

In [66]:
average = real_estate[['1㎡당금액(만원)']].mean(axis=1)
average.shape

(719,)

In [68]:
# 음... average는 구했는데... 동별로 어떻게 DF 로 하지?
real_estate.groupby(by="시군구").mean()

                  1㎡당금액(만원)
시군구
서울특별시 강남구 논현동    665.346661
서울특별시 강남구 대치동   1300.202198
서울특별시 강남구 도곡동    971.481022
서울특별시 강남구 삼성동    959.608783
서울특별시 강남구 수서동    885.825694
서울특별시 강남구 신사동   1515.749001
서울특별시 강남구 역삼동   1609.181801
서울특별시 강남구 일원동    619.237148
서울특별시 강남구 청담동   1674.624524
서울특별시 강동구 고덕동    251.256281
서울특별시 강동구 길동     315.711397
서울특별시 강동구 둔촌동   2189.878885
서울특별시 강동구 명일동    417.980723
서울특별시 강동구 성내동   1590.209910
서울특별시 강동구 암사동    127.877238
서울특별시 강동구 천호동    596.932295
서울특별시 강북구 미아동    400.000000
서울특별시 강북구 번동     372.402979
서울특별시 강북구 수유동    472.945069
서울특별시 강서구 가양동    236.167341
서울특별시 강서구 공항동    641.299955
서울특별시 강서구 내발산동   395.758865
서울특별시 강서구 등촌동    540.149012
서울특별시 강서구 마곡동   1093.624741
서울특별시 강서구 방화동    212.417453
서울특별시 강서구 화곡동    444.388012
서울특별시 관악구 봉천동   1178.451178
서울특별시 관악구 신림동    538.322063
서울특별시 광진구 구의동    360.979451
서울특별시 광진구 군자동    214.724512
...                     ...
서울특별시 종로구 인사동   5985.711527
서울특별시 종로구 인의동   3129.890454
서울특별시 종로구 장사동    361.094933
서울특별시 종로구 종로2가  5271.360469
서울특별시 종로구 종로4가   730.047335
서울특별시 종로구 종로5가   571.778640
서울특별시 종로구 종로6가  4250.000000
서울특별시 종로구 혜화동    944.104913
서울특별시 중구 남창동     690.227722
서울특별시 중구 다동     1458.182663
서울특별시 중구 산림동    4109.947644
서울특별시 중구 서소문동   1119.418380
서울특별시 중구 순화동    1384.307750
서울특별시 중구 신당동    2933.882018
서울특별시 중구 오장동    2244.309997
서울특별시 중구 을지로3가  4527.630252
서울특별시 중구 을지로6가  1741.248061
서울특별시 중구 을지로7가  2896.735500
서울특별시 중구 의주로1가  2182.153468
서울특별시 중구 저동1가   2373.955632
서울특별시 중구 중림동     593.658332
서울특별시 중구 충무로2가  8045.977011
서울특별시 중구 충무로4가   404.508601
서울특별시 중구 충무로5가   492.656059
서울특별시 중구 황학동     736.580308
서울특별시 중구 회현동1가  2712.477396
서울특별시 중구 흥인동     582.154600
서울특별시 중랑구 망우동    344.366108
서울특별시 중랑구 묵동     739.033392
서울특별시 중랑구 신내동   1267.973856

[191 rows x 1 columns]