In [51]:
import pandas as pd
import numpy as np
from datetime import date

In [52]:
# csv 불러오기
df = pd.read_csv('sangsang_2017.csv')
df.head()

,생생정보통,대풍만두,20170103,2017. 1. 8. 18:34,안동 사대부찜닭 생생정보통에 나온 대풍만두 다녀왔어요
0,생생정보통,대풍만두,20170103,2017. 1. 27. 21:00,"안동구시장찐빵맛집, 생생정보통 대풍만두"
1,생생정보통,대풍만두,20170103,2017. 1. 3. 16:20\n\t,오즈패밀리 KBS 생생정보 1월3일 맛집 - 흑미 복분자 찐빵(대풍만두)
2,생생정보통,대풍만두,20170103,2017. 1. 3. 18:51,"◈ 안동 찐빵 만두 맛집 공유~* , 2tv 저녁 생생정보 안동 구시장 찐빵 맛..."
3,생생정보통,대풍만두,20170103,2017. 1. 31. 14:51\n\t,"안동 맛집-찐빵맛집,만두맛집,생생정보<상주곶감본가>"
4,생생정보통,대풍만두,20170103,2017. 1. 24. 15:22\n\t,"[부산맛집/장산맛집] 해운대맛집 ""대풍밀면"""

In [53]:
# 칼럼 채우기
df.columns = ['방송', '식당', '방영일', '포스팅일', '제목']
df.head()

,방송,식당,방영일,포스팅일,제목
0,생생정보통,대풍만두,20170103,2017. 1. 27. 21:00,"안동구시장찐빵맛집, 생생정보통 대풍만두"
1,생생정보통,대풍만두,20170103,2017. 1. 3. 16:20\n\t,오즈패밀리 KBS 생생정보 1월3일 맛집 - 흑미 복분자 찐빵(대풍만두)
2,생생정보통,대풍만두,20170103,2017. 1. 3. 18:51,"◈ 안동 찐빵 만두 맛집 공유~* , 2tv 저녁 생생정보 안동 구시장 찐빵 맛..."
3,생생정보통,대풍만두,20170103,2017. 1. 31. 14:51\n\t,"안동 맛집-찐빵맛집,만두맛집,생생정보<상주곶감본가>"
4,생생정보통,대풍만두,20170103,2017. 1. 24. 15:22\n\t,"[부산맛집/장산맛집] 해운대맛집 ""대풍밀면"""

In [54]:
# 포스팅일이 크롤링 되지 않은 경우 제외하기
df = df[df['포스팅일'].isnull() == False]

# 제외된 행으로 인해 빈 index를 다시 채워주기
# (여기서 다시 안채워주면 빈 index에 null값이 채워진다)
df = df.reset_index()

In [56]:
# 방영일 date 형식으로 바꾸기
def get_date_from_b_date(df_column):
    b_date = []
    for data in df_column:
        year = data[:4]
        month = data[4:6]
        day = data[6:8]
        single_date = date(int(year), int(month), int(day))
        b_date.append(single_date)

    return pd.Series(b_date)

df['방영일'] = df['방영일'].astype(str)
df['방영일'] = get_date_from_b_date(df['방영일'])
df.head(3)

,index,방송,식당,방영일,포스팅일,제목
0,0,생생정보통,대풍만두,2017-01-03,2017. 1. 27. 21:00,"안동구시장찐빵맛집, 생생정보통 대풍만두"
1,1,생생정보통,대풍만두,2017-01-03,2017. 1. 3. 16:20\n\t,오즈패밀리 KBS 생생정보 1월3일 맛집 - 흑미 복분자 찐빵(대풍만두)
2,2,생생정보통,대풍만두,2017-01-03,2017. 1. 3. 18:51,"◈ 안동 찐빵 만두 맛집 공유~* , 2tv 저녁 생생정보 안동 구시장 찐빵 맛..."

In [57]:
# 끝까지  date 형식으로 변환됨을 확인
df.tail(3)

,index,방송,식당,방영일,포스팅일,제목
10179,10238,생생정보통,해신247,2017-12-25,2017. 12. 31. 14:50\n\t,거제도 가는중~~^^
10180,10239,생생정보통,해신247,2017-12-25,2017. 12. 22. 13:26\n\t,제주올레 11코스(모슬포~무릉)
10181,10240,생생정보통,해신247,2017-12-25,2018. 1. 12. 22:13\n\t,군산시 공무원임용서 1월 15일자 인사발령사항

In [58]:
# 포스팅 날짜 date 형식으로 바꾸기
p_date = []
df['포스팅일'] = df['포스팅일'].astype(str)
for data in df['포스팅일']:
    date_components = data.split('.')
    year = date_components[0]
    month = date_components[1]
    day = date_components[2]
    single_date = date(int(year), int(month), int(day))
    p_date.append(single_date)
    
df['포스팅일'] = pd.Series(p_date)
df.head(3)

,index,방송,식당,방영일,포스팅일,제목
0,0,생생정보통,대풍만두,2017-01-03,2017-01-27,"안동구시장찐빵맛집, 생생정보통 대풍만두"
1,1,생생정보통,대풍만두,2017-01-03,2017-01-03,오즈패밀리 KBS 생생정보 1월3일 맛집 - 흑미 복분자 찐빵(대풍만두)
2,2,생생정보통,대풍만두,2017-01-03,2017-01-03,"◈ 안동 찐빵 만두 맛집 공유~* , 2tv 저녁 생생정보 안동 구시장 찐빵 맛..."

In [59]:
df.tail(3)

       index     방송     식당         방영일        포스팅일                         제목
10179  10238  생생정보통  해신247  2017-12-25  2017-12-31                거제도 가는중~~^^
10180  10239  생생정보통  해신247  2017-12-25  2017-12-22          제주올레 11코스(모슬포~무릉)
10181  10240  생생정보통  해신247  2017-12-25  2018-01-12  군산시 공무원임용서 1월 15일자 인사발령사항

In [60]:
# 방영일과 포스팅일 날짜 차이 구하기
def get_days_diff(col_days_diff, col_b_day, col_p_day):
    col_days_diff = col_p_day - col_b_day
    col_days_diff = col_days_diff.astype(str).str.findall(r'(\-?\d+)\s')
    days_list = []
    for days in col_days_diff:
        days_list.append(int(days[0]))
    return days_list

df['days_diff'] = pd.Series()
df['days_diff'] = get_days_diff(df['days_diff'], df['방영일'], df['포스팅일'])

In [61]:
df.head(3)

,index,방송,식당,방영일,포스팅일,제목,days_diff
0,0,생생정보통,대풍만두,2017-01-03,2017-01-27,"안동구시장찐빵맛집, 생생정보통 대풍만두",24
1,1,생생정보통,대풍만두,2017-01-03,2017-01-03,오즈패밀리 KBS 생생정보 1월3일 맛집 - 흑미 복분자 찐빵(대풍만두),0
2,2,생생정보통,대풍만두,2017-01-03,2017-01-03,"◈ 안동 찐빵 만두 맛집 공유~* , 2tv 저녁 생생정보 안동 구시장 찐빵 맛...",0

In [62]:
df.tail(3)

,index,방송,식당,방영일,포스팅일,제목,days_diff
10179,10238,생생정보통,해신247,2017-12-25,2017-12-31,거제도 가는중~~^^,6
10180,10239,생생정보통,해신247,2017-12-25,2017-12-22,제주올레 11코스(모슬포~무릉),-3
10181,10240,생생정보통,해신247,2017-12-25,2018-01-12,군산시 공무원임용서 1월 15일자 인사발령사항,18